name: Deploy
on:
  push:
    branches: [ 'master', 'dev' ]
  pull_request:
    branches: [ 'master' ]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Flake8 lint
        run: |
          pip install --upgrade pip;
          pip install flake8;
          flake8 --ignore=E501,F401,W503,W504 .
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    name: Deploy to server
    steps:
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd gha-explore
          git pull
          cat oop.py


