name: Deploy
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Flake8 lint
        run: |
          pip install --upgrade pip;
          pip install flake8;
          flake8 --ignore=E501,F401,W503,W504 .
